//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AguaArarasEntities : DbContext
    {
        public AguaArarasEntities()
            : base("name=AguaArarasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Endereco> Enderecos { get; set; }
        public virtual DbSet<Pessoa> Pessoas { get; set; }
        public virtual DbSet<Telefone> Telefones { get; set; }
        public virtual DbSet<Cota> Cotas { get; set; }
        public virtual DbSet<Recibo> Recibos { get; set; }
        public virtual DbSet<Movimento> Movimentos { get; set; }
    
        public virtual int sp_ColetaAdd(Nullable<int> reciboID, Nullable<System.DateTime> data)
        {
            var reciboIDParameter = reciboID.HasValue ?
                new ObjectParameter("ReciboID", reciboID) :
                new ObjectParameter("ReciboID", typeof(int));
    
            var dataParameter = data.HasValue ?
                new ObjectParameter("Data", data) :
                new ObjectParameter("Data", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ColetaAdd", reciboIDParameter, dataParameter);
        }
    
        public virtual ObjectResult<sp_Movimentos_Result> sp_Movimentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Movimentos_Result>("sp_Movimentos");
        }
    
        public virtual ObjectResult<sp_Balanco_Result> sp_Balanco(string part)
        {
            var partParameter = part != null ?
                new ObjectParameter("part", part) :
                new ObjectParameter("part", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Balanco_Result>("sp_Balanco", partParameter);
        }
    
        public virtual ObjectResult<sp_Xtab_Result> sp_Xtab(string part)
        {
            var partParameter = part != null ?
                new ObjectParameter("part", part) :
                new ObjectParameter("part", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Xtab_Result>("sp_Xtab", partParameter);
        }
    
        public virtual ObjectResult<sp_Extrato_Result> sp_Extrato(Nullable<System.DateTime> inicio, Nullable<System.DateTime> termino)
        {
            var inicioParameter = inicio.HasValue ?
                new ObjectParameter("Inicio", inicio) :
                new ObjectParameter("Inicio", typeof(System.DateTime));
    
            var terminoParameter = termino.HasValue ?
                new ObjectParameter("Termino", termino) :
                new ObjectParameter("Termino", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Extrato_Result>("sp_Extrato", inicioParameter, terminoParameter);
        }
    
        public virtual int sp_ManutencaoAdd()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ManutencaoAdd");
        }
    
        public virtual ObjectResult<string> sp_TiposMovimento()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_TiposMovimento");
        }
    }
}
