//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimento
    {
        public int ID { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> ReciboID { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Historico { get; set; }
        public decimal Valor { get; set; }
        public string Observacoes { get; set; }
    
        public virtual Recibo Recibo { get; set; }
    }
}
