//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pessoa()
        {
            this.Enderecos = new HashSet<Endereco>();
            this.Telefones = new HashSet<Telefone>();
            this.Cotas = new HashSet<Cota>();
        }
    
        public int ID { get; set; }
        public bool Ativo { get; set; }
        public string Tratamento { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string EMail { get; set; }
        public byte Tomadas { get; set; }
        public byte RuaAraras { get; set; }
        public string Numero { get; set; }
        public byte Cobranca { get; set; }
        public bool Recibo { get; set; }
        public bool Atualizar { get; set; }
        public string Observacoes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Endereco> Enderecos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefone> Telefones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cota> Cotas { get; set; }
    }
}
