//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recibo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recibo()
        {
            this.Cotas = new ObservableListSource<Cota>();
            this.Movimentos = new ObservableListSource<Movimento>();
        }
    
        public int ID { get; set; }
        public bool Extra { get; set; }
        public byte Numero { get; set; }
        public System.DateTime Emissao { get; set; }
        public System.DateTime Vencimento { get; set; }
        public decimal Cota { get; set; }
        public byte Meses { get; set; }
        public string Descricao { get; set; }
        public string Observacoes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Cota> Cotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Movimento> Movimentos { get; set; }
    }
}
